# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'fede2WSL'

steps:
- task: ArtifactoryDocker@1
  inputs:
    command: 'pull'
    artifactoryService: 'newConnection'
    sourceRepo: 'prova2'
    imageName: 'https://a0muixhnkluno/ui/admin/repositories/local/prova2/'
    username: fede
    password: ;+i5}SAf^+x3F;*
- task: Docker@2
  inputs:
    containerRegistry: 'fedeRegistry'
    repository: 'https://a0muixhnkluno.jfrog.io/artifactory/prova2/'
    command: 'build'
    Dockerfile: 'prova2/nginx/Dockerfile'
    tags: 'latest'
- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'newConnection'
    targetRepo: 'prova2'
    imageName: 'https://a0muixhnkluno.jfrog.io/artifactory/prova2/'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    username: fede
    password: ;+i5}SAf^+x3F;*
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'newConnection'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    username: fede
    password: ;+i5}SAf^+x3F;*
- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'newConnection'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true
