# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: sourceRepo
    displayName: Source Repository
    type: string
    default: 'prova2'
  - name: containerRegistry
    displayName: Container Registry
    type: string
    default: 'fedeRegistry'
  - name: dockerfileLocation
    displayName: Dockerfile Location
    type: string
    default: '/nginx/Dockerfile'
  - name: targetRepo
    displayName: Target Repository
    type: string
    default: 'nginx'

variables:
  - name: sourceRepo
    value: ${{ parameters.sourceRepo }}
  - name: containerRegistry
    value: ${{ parameters.containerRegistry }}
  - name: dockerfileLocation
    value: ${{ parameters.dockerfileLocation }}
  - name: targetRepo
    value: ${{ parameters.targetRepo }}
  - name: imageName
    value: 'https://a0muixhnkluno.jfrog.io/artifactory/${{ variables.sourceRepo }}/'
  - name: buildName
    value: '$(Build.DefinitionName)'
  - name: buildNumber
    value: '$(Build.BuildNumber)'

jobs:
- job: ParallelJobs
  displayName: Parallel Jobs
  pool: 'fede2WSL'

  steps:
  - task: ArtifactoryDocker@1
    displayName: Pull Container
    inputs:
      command: 'pull'
      artifactoryService: 'newConnection'
      sourceRepo: ${{ variables.sourceRepo }}
      imageName: ${{ variables.imageName }}

  - task: Docker@2
    displayName: Build Container
    inputs:
      containerRegistry: ${{ variables.containerRegistry }}
      repository: ${{ variables.sourceRepo }}
      command: 'build'
      Dockerfile: ${{ variables.dockerfileLocation }}
      tags: 'latest'

  - task: ArtifactoryDocker@1
    displayName: Push Container
    inputs:
      command: 'push'
      artifactoryService: 'newConnection'
      targetRepo: ${{ variables.targetRepo }}
      imageName: ${{ variables.imageName }}
      collectBuildInfo: true
      buildName: ${{ variables.buildName }}
      buildNumber: ${{ variables.buildNumber }}

  - task: ArtifactoryPublishBuildInfo@1
    displayName: Publish Build Info
    inputs:
      artifactoryService: 'newConnection'
      buildName: ${{ variables.buildName }}
      buildNumber: ${{ variables.buildNumber }}

  - task: ArtifactoryXrayScan@1
    displayName: Xray Scan
    inputs:
      artifactoryService: 'newConnection'
      buildName: ${{ variables.buildName }}
      buildNumber: ${{ variables.buildNumber }}
      allowFailBuild: true
